[package]
name = "aho-corasick"
version = "0.1.0"
edition = "2024"

[lib]
name = "aho_corasick"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.27.2"

[dev-dependencies]
rand = "0.9.2"
rand_distr = "0.5.1"
