[project]
name = "aho-corasick"
version = "0.1.0"
description = "Aho Corasick algorithm for efficient text searches - implemented in Rust!"
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = []

[dependency-groups]
dev = [
    "maturin>=1.10.2,<2",
]
